### ISSUE TITLE
Version of Unity supported

### ISSUE THREAD

**Issue by fylux** [popcron/gizmos#1]
Why does it only support 2018.3?

**Comment by popcron** [comment]
It does work on other versions (theoretically on any version).

The reason why it states 2018.3.x is because Unity has added support for git packages for UPM in that version, any version under will not load the package if using the manifest.json file.

Otherwise, you can download the entire repository and add it to your `Packages/com.popcron.gizmos` folder manually if using a lower version.

**Comment by fylux** [comment]
Thanks for the clarification. Also it is worth noticing that there is a function that uses the "out" keyword in a way that is only supported in C# 7.

**Comment by popcron** [comment]
Thanks for the heads up, just removed that dependency.
