### ISSUE TITLE
Gizmos.Camera

### ISSUE THREAD

**Issue by smygarn** [popcron/gizmos#12]
The Gizmos.Circle doesn't rotate towards the camera! It doesn't work if you manually set Gizmos.Camera as well.

Workaround, use this code:

        Gizmos.Circle(transform.position, 0.2f, Quaternion.LookRotation(transform.position - Camera.main.transform.position), Color.white);

**Comment by popcron** [comment]
This appears to be because the camera value in the static property is really a filter, if it's null it let's the main camera render, otherwise the specified camera. (according to the gizmo instance code) 

The circle drawer on the other hand draws towards the current rendering camera, which at the time of the call it could be either the camera specified or the scene view camera. Some confusion going on there.

Likely fix would be to instead pass a boolean asking the final data to billboard towards the camera instead of setting the rotation at the moment of the call, because it's likely trying to billboard towards the wrong camera. An oversight for sure, I'll see if I can do a fix this week, thanks for the issue.

**Comment by popcron** [comment]
Btw, pro tip: get a reference to the main camera instead of using camera.main because that does a find object call every time.

**Comment by popcron** [comment]
Closing this because I added an overload to the circle method to do exactly that for you
